[package]
name = "bill_split_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web    = "4"
actix-files  = "0.6"
include_dir  = "0.7"
mime_guess   = "2"
serde        = { version = "1.0", features = ["derive"] }
serde_json   = "1.0"
thiserror    = "1.0"
